### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '-sn': '-sn'

### ISSUE THREAD

**Issue by 1273082756** [SIPp/pysipp#71] opened 2021-07-08 08:24 UTC
import pysipp
pysipp.client(auth_username='xxx', auth_password='xxx')()

The following problems occur

FileNotFoundError: [Errno 2] No such file or directory: '-sn': '-sn'

**Comment by 1273082756** [comment] 2021-07-08 08:25
Python 3.6.8 (default, Aug 24 2020, 17:57:11) 
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysipp
>>> pysipp.client(auth_username='xxx', auth_password='xxx')()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pysipp/agent.py", line 75, in __call__
    raise_exc=raise_exc, **kwargs
  File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.6/site-packages/pysipp/__init__.py", line 236, in pysipp_run_protocol
    block=block, timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pysipp/launch.py", line 67, in __call__
    stderr=sp.PIPE
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '-sn': '-sn'

**Comment by kontsaki** [comment] 2021-08-04 08:01
hey @1273082756  do have you `sipp` installed on the machine running the tests?

**Comment by goodboy** [comment] 2022-12-19 16:55
Yes this is duplicate of #77.

**Closed by goodboy** 2022-12-19 16:55 UTC
Labels: duplicate
