### ISSUE TITLE
Can't import pysipp after install

### ISSUE THREAD

**Issue by RichParker734** [SIPp/pysipp#34] opened 2018-06-19 14:36 UTC
I just installed pysipp for the first time on windows 10 (Python2.7) using:
   pip install git+git://github.com/SIPp/pysipp.git
And after it installed, I tried your example script and got an error.  Basically opening a python prompt and typing "import pysipp" generates the following error:

C:\pyfiles>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysipp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pysipp\__init__.py", line 23, in <module>
    from . import launch, report, plugin, netplug, agent
  File "C:\Python27\lib\site-packages\pysipp\launch.py", line 24, in <module>
    class PopenRunner(object):
  File "C:\Python27\lib\site-packages\pysipp\launch.py", line 35, in PopenRunner
    poller=select.epoll,
AttributeError: 'module' object has no attribute 'epoll'

Any ideas how to fix this?
Thanks!

**Comment by vodik** [comment] 2018-06-21 16:20
Hey, so the problem here is that `epoll` is a Linux subsystem: https://docs.python.org/3/library/select.html#select.epoll

I'd be more then happy to support Windows/OSX if we got some patches for it. In the meanwhile, this is effectively a duplicate of #17.

**Closed by vodik** 2018-06-21 16:20 UTC

**Comment by tgoodlet** [comment] 2018-06-21 17:44
@vodik hmm too bad @RichParker734 isn't on py3 because then we should be able to just delegate to [`selectors`](https://docs.python.org/3.5/library/selectors.html#module-selectors)..

**Comment by tgoodlet** [comment] 2018-08-20 21:38
@vodik @wdoekes actually what do you two think about cutting py2.7 support?

**Comment by vodik** [comment] 2018-08-21 00:35
No contest to the idea. Don't have skin in the game.

I'm maintaining two projects that are using pysipp/sipp, but haven't moved them to newer versions of either sipp or pysipp and they can continue on as they are.

I've largely moved on to aiosip as a pysipp replacement.

**Comment by wdoekes** [comment] 2018-08-21 08:35
Fine with me. I use pysipp in only one instance and there I probably already use py3.
